spring:
  profiles: dev

# Database configuration for development
spring.datasource:
  url: jdbc:mysql://dev-database-url:3306/dev_database_name
  username: dev_db_username
  password: dev_db_password

# Other dev-specific configurations here
