spring:
  profiles: test

# Database configuration for test
spring.datasource:
  url: jdbc:mysql://test-database-url:3306/test_database_name
  username: test_db_username
  password: test_db_password

# Other test-specific configurations here
