spring:
  profiles: prod

# Database configuration for production
spring.datasource:
  url: jdbc:mysql://prod-database-url:3306/prod_database_name
  username: prod_db_username
  password: prod_db_password

# Other prod-specific configurations here
